### ISSUE TITLE
key not found if first line of file

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#100]
I just created a new test repo with `src/a.js` as the only source file with just 2 lines

```
l("ONE");
l("TWO");
```

The first `l10ns update` consistently misses the first line. Adding a line with a comment above it works around.

**Comment by tinganho** [comment]
Fixed in https://github.com/tinganho/l10ns/commit/d50539f8ad4ae1bcc71baf10a943cd4977ec8507

**Comment by focusaurus** [comment]
nice. thanks!
