### ISSUE TITLE
More verbose error messages.

### ISSUE THREAD

**Issue by nmn** [tinganho/l10ns#102]
L10ns is AWESOME.

It has been a pleasure to use it this whole time. But now, I get an error when I run `l10ns update'

It simply says:
`[error] Localizations update failed`

L10ns should show more descriptive errors, so I can actually do something to fix it.

**Comment by nmn** [comment]
Never mind, found --stack flag.

**Comment by tinganho** [comment]
thanks @nmn. I'm just curious what the stack shows?

**Comment by nmn** [comment]
genuine error in my code. Stack traces were super accurate. I just think this flag should be ON by default. We are all developers. We all like good error messages. This is why I even created the issue before I hunted for a flag.

The actual error was that I was calling the same key with different values, (second arg, obj)

**Comment by tinganho** [comment]
@nmn Ok that error should actually be displayed regardless of stack option. I will fix it. Thanks for reporting.

**Comment by tinganho** [comment]
Ok fixed in l10ns@2.0.20

**Comment by nmn** [comment]
Thanks!
