### ISSUE TITLE
compiler should not delete files

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#103]
https://github.com/tinganho/l10ns/blob/master/plugins/javascript/compiler.js#L77

That is deleting some other .js files that just happen to be in the same "build" directory where the l10ns compiler output goes. Not sure I see the value in deleting the files. Just overwrite them, add new ones, and if a locale is removed, I don't need l10ns to delete the file for me.

In general this violates my expectations and "principle of least surprise". I expect the compiler to **create** new files, not delete. I expect a command like "clean" to delete.

**Comment by tinganho** [comment]
I added the automatic deletion before because when I deleted a language in `l10ns.json` I wanted it to reflect on the compiled folder. But it seems like this approach doesn't follow best practice.

I will add a clean command instead in the coming days. I can ping you when I'm done.
