### ISSUE TITLE
install crashing with request/cldr-data/boom issue

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#104]
I'm still seeing this with 2.0.21

```
> cldr-data@26.0.10 install /home/footprintid/Footprintid/node_modules/l10ns/node_modules/cldr-data
> node install.js

\
module.js:340
    throw err;
          ^
Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/footprintid/Footprintid/node_modules/l10ns/node_modules/request/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! cldr-data@26.0.10 install: `node install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the cldr-data@26.0.10 install script.
npm ERR! This is most likely a problem with the cldr-data package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls cldr-data
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.2.0-77-virtual
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! cwd /home/footprintid/Footprintid
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by focusaurus** [comment]
package.json in master still says 2.0.18. Are you doing the commit/tag/push/publish routine fully?

**Comment by tinganho** [comment]
@focusaurus can you try to install now?

**Comment by tinganho** [comment]
Im trying to follow that workflow. But I must admit that some times I miss to make git tags.

**Comment by focusaurus** [comment]
Well now I think npm knows that the latest version is 2.0.22. I think there may have been some lag there. I have had a local install succeed but on my server I'm seeing this, which I'm not sure what it is but my guess is the linux OOM killer is killing the process during the unzip of cldr-data.

```
GET `http://www.unicode.org/Public/cldr/26.0.1/json-full.zip`
  [========================================] 100% 0.0s
Received 52540K total.
Unpacking it into `./`
Killed
```

This has been a struggle. Let me see if I can get past this one.

**Comment by focusaurus** [comment]
Sigh: https://github.com/cthackers/adm-zip/issues/129

**Comment by tinganho** [comment]
hmm strange. The downloaded file is not that bigger than 1GB. I'm getting a successful install in ubuntu?

**Comment by focusaurus** [comment]
It's 51MB on disk in the zip file and 473MB when extracted. I worked around it by tarring up my local node_modules and manually installing that on the server, but I suspect strongly that the adm-zip package is very badly implemented. Keep in mind this is a could VM that is already running linux, mysql, nginx, so it's not like there's gigs and gigs of free memory available.

It would be nice to get this more reliable in the near term and maybe in the longer term restrict the download to only those supported by the application (assuming it's even available on a per-locale basis which it may not in fact be).

**Comment by focusaurus** [comment]
But anyway, the 2.0.22 version when I finally got npm to really install  it fixed the 'boom' issue so you can close this. Thanks as always for your assistance!

**Comment by tinganho** [comment]
@focusaurus you're welcome
