### ISSUE TITLE
Allow option to leave removed keys in the data files

### ISSUE THREAD

**Issue by focusaurus** [tinganho/l10ns#105]
```
[added] L_DROPDOWN__PENICILLIN
The key "L_DROPDOWN__HOME" is now gone in source.
What do you want to do with it?
[1] - migrate to "L_DROPDOWN__PENICILLIN"
[d] - delete
[1,d] (d)?
```

I need an option here to just leave the data. I'm not sure why folks would want discarding translations as a normal part of there workflow. As I mentioned in the other issue, not 100% of all keys are in source code. Some come from a DB and sometimes different installs have slightly different data sets and I need to not have l10ns discard translations in this scenario.

**Comment by tinganho** [comment]
>I'm not sure why folks would want discarding translations as a normal part of there workflow

@focusaurus One of my biggest pain of using other i18n tools where that the localization storage contained so much unused localization. 

Let me think about this problem. I'm sure we can solve it in a good way.

**Comment by focusaurus** [comment]
I'd rather see them marked as inactive and have a separate "purge" command or something. Features get removed and re-added but I think recovering old translations from git would be a royal pain given the json file format.

Overall I think the tool's orientation is currently overly "let me handle everything" and I'd rather have access to some additional focused commands. At the moment "update" makes me nervous and I carefully inspect the git diff (which is not easy for these files) to make sure I'm not throwing away translations.

**Comment by tinganho** [comment]
I think I'm going to not accept this suggestion. One of the major paint points is unused localizations.

It outputs deleted keys on the standard output right now to mitigate any problems .
