### ISSUE TITLE
npm install stops after unicode download

### ISSUE THREAD

**Issue by alawatthe** [tinganho/l10ns#106]
Everytime I am trying to ```npm install l10ns```, the installation stops after downloading the unicode file (the process is still alive, but nothing is happening):

```
->npm install l10ns -g
 
> cldr-data@26.0.10 install /Users/alawatthe/.nvm/versions/io.js/v1.6.4/lib/node_modules/l10ns/node_modules/cldr-data
> node install.js

GET `http://www.unicode.org/Public/cldr/26.0.1/json-full.zip`
  [========================================] 100% 0.0s
```

I tried it multiple times with io.js v1.6.4 and node.js v0.12.2 on two Macs with OS X Yosemite 10.10.2.

Am I doing something wrong? Do I have to do something before installing l10ns?

**Comment by tinganho** [comment]
@alawatthe how long are you waiting? Actually the progress bar is way off. After it is downloading it is actually extracting.

**Comment by alawatthe** [comment]
@tinganho I waited about 10-15 minutes each time. But, I tried again just now and everything worked perfectly (in about 4 minutes). Don't know what happened yesterday. Sorry for bothering you :-/
