### ISSUE TITLE
Wrong output path computed

### ISSUE THREAD

**Issue by akayami** [tinganho/l10ns#109]
Hi, 

I've been testing l10ns and I've noticed that it is compiling the wrong output path.

The problem is located in: 
plugins/javascript/compiler.js 
Line: 115 and line 150. 

In both cases, path.join(project.root, project.output) causes the project.root contents to be there twice, because it is already set in project.output earlier. 

Would you like a pull request or do you prefer to fix it yourself ?

Thanks.

**Comment by tinganho** [comment]
I don't quite understand the problem?

FYI one is compiling the bundled languages `all.js` and the other is compiling each language.

**Comment by akayami** [comment]
Hi,

Let me try to be clear. The problem actually starts in:
libraries/index.js
Line 150:
```
else if(!/^\//.test(project.output) && !/^\w\:/.test(project.store)) {
    project.output = path.join(project.root, project.output);
}
```
where project.root is prepended to project.output.

Then, in:
plugins/javascript/compiler.js 
Line: 115 and line 150:
```
var filePath = path.join(project.root, project.output) + '/' + language + '.js';
```
and 
```
var filePath = path.join(project.root, project.output) + '/all.js';
```

project.root is prepended again to project output.

Assuming project root is:
```
/path/root
```
and project output is:
```
output
```
the filePath will be: 
```
/path/root/path/root/output/all.js
```
and so on

**Comment by tinganho** [comment]
@akayami can you try l10ns@2.1.1? I had this issue fixed.
