### ISSUE TITLE
Exception on init

### ISSUE THREAD

**Issue by ray007** [tinganho/l10ns#116]
I tried to follow instructions, but when executing `l10ns init` I only get an error:
```
This tool will walk you through creating a l10ns project.
It only covers the most common items, and tries to guess sane defaults.

Press ^C at any time to quit.

Project name(test)?events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn C:\prg\msys64\usr\bin\node ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```
Just happened with `l10ns` version 2.2.5 fresh after npm install.

**Comment by tinganho** [comment]
@ray007 I'm not getting this error on my Mac. I will try it on a Windows.

**Comment by tinganho** [comment]
@ray007 I cannot reproduce this issue? I think there is something wrong with your node?

>spawn C:\prg\msys64\usr\bin\node ENOENT

**Comment by ray007** [comment]
Hmm, strange.
Just a few days, and it now also works here from a CMD prompt. Only in msys-shell it still fails.
