### ISSUE TITLE
Implement normal (short, medium, long and full) date formats

### ISSUE THREAD

**Issue by rhalukongor** [tinganho/l10ns#117]
It is hard to have a consistent date format across a project when you specify date formatting with the format strings. Implementing ICU's [normal date formats](http://userguide.icu-project.org/formatparse/datetime) would help us to do so.

I could try to implement this however I have little knowledge about CLDR tables. I'd be happy to do so if someone guides me a little bit.

**Comment by tinganho** [comment]
You will get the CLDR tables when you run `npm install` under node_modules. It is using `cldr-data`.

**Comment by rhalukongor** [comment]
Thanks @tinganho. When I check the table data I found out that there are three types of normal formats: For date, time and datetime.How do you suggest implementing those?

```
{variable, date, short}
{variable, time, full}
{variable, datetime, long}
```
This is what comes to mind first but isn't this introducing two new message formats? Any suggestions on this?

**Comment by tinganho** [comment]
I will take a look first

**Comment by tinganho** [comment]
Just curious where do you found the data? I can't find the corresponding CLDR data.

**Comment by tinganho** [comment]
Ok I found it now, under `/main/en/ca-gregorian.json` and then `main.en.dates.gregorian.dateFormats`. Just use the properties from there. There is already logics that resolves to the right file. Please also check maybe 10 languages under main and see if they contain all four properties `full`, `long`, `medium` and `short`.

**Comment by rhalukongor** [comment]
Ok I'll do a few tests and be back but first thing is first:
I need some help setting up the project.
What is with the 'cldr-data/defaultContent.json'?
Can't run the tests because that file is not found and discovered [your issue](https://github.com/rxaviers/cldr-data-downloader/issues/14 ) while googling for it... Is this an ongoing issue?

**Comment by rhalukongor** [comment]
Ok solved it.
```
cd cldr-data &&  npm install
```
for the reference.

**Comment by tinganho** [comment]
I don't recall what  `defaultContent.json` did. But it was being handled in `cldr-data` or some of its dependencies.

**Comment by tinganho** [comment]
Please also stick with the current syntax:
```
{variable, date, [full,short,medium,long]}
```

**Comment by tinganho** [comment]
@rhalukongor I see what you mean now with the three types `date`, `time` and `dateTime`. Let me think a little bit about. You original suggestion seem fine to me. Let me sleep on it.
