### ISSUE TITLE
Saving should move to next untranslated token

### ISSUE THREAD

**Issue by wemcdonald** [tinganho/l10ns#118]
I love the interface you've created, but it's tedious to have to click "Home" (or back) to advance. It would be great if clicking Save could either
* Advance to the next untranslated token, if it exists, or
* Go back to the index.

**Comment by tinganho** [comment]
Got back to the index might be appropriate on this one. Though it would come in a potential `3.0` release.

**Comment by tinganho** [comment]
I think going back to the index is the most appropriate one. I can maybe add some small recommended next translations.
