### ISSUE TITLE
default translation value

### ISSUE THREAD

**Issue by fariza** [tinganho/l10ns#120]
Hi

I am pretty sure I'm missing something basic here, but coming from Django, and the way it collects and compile strings for translations. In Django the default value to the `gettext` function is used as key. 
I understand the advantage of using a different key, but actually it is pretty useful to have the default value also there.
Is there a way to pass a default value to the `l` function?

Thanks

**Comment by tinganho** [comment]
Hi @fariza, I also came from gettext. And I thought that feature was a miss-use. Let me clarify the missuseness:

I believe localization should be referenced with keys that should be the name of a localization text. So you write:

```
l('SEARCH->INPUT_PLACEHOLDER');
```
The above is a name of a textfield on a search input placeholder. But you could also write the text value directly:
```
l('Search users');
```
And L10ns could use the localization key as a localizalization value, i.e. default translation value. But what if one developer decides to change the value of the input field:
```
Search...
```
What happened, is now the `l('Search users')` is not a good representative of the localization for the search input.

I believe referencing by name and not by value is the correct way. And adding default translation value will only help people missuse it.

**Comment by fariza** [comment]
Hi @tinganho thanks for your prompt answer

I understand what you mean and I agree that the name space is very important, but the problem (at least for me), is that this imposes a workflow that breaks my concentration. 

Suppose I'm writing a button, in that precise moment I am thinking about callbacks etc.. and I add the string to be translated, save... and I want to see my result immediately.
Without default value, I have to stop thinking about callbacks, I have to go update the strings, add the default value, compile the strings and finally be able to see my result.

It is not a big deal when most of your code is already in place and you start translating, but if you build with translations in mind, it becomes a burden.

Let's say its not a default value, it's a **Translation place holder**
