### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by reneklacan** [tinganho/l10ns#121]
Hi @tinganho, just wanted to ask if you have any future plans for this project or did you lose your interest in it?

**Comment by tinganho** [comment]
@reneklacan It's alive. I use it everyday. I care about L10ns deeply. I fix bugs as soon as possible. There doesn't seem to have report any for a while, thus my latest commit was a long time ago.

Though my fashion of doing things is not continuously. I write major versions each 1-2 years, this is my style of working. Just doing L10ns alone was a big thing, itself is architected as a compiler. So recently I have contributed to Typescript to know more about compiler architecture to later architect L10ns more perfectly. 

I have big plans for the next version v3 of L10ns. Which will support other programming languages. I don't plan on any API changes on V3. So you can go ahead and use L10ns. 

I know people look at latest commit to judge a project. But I have to say API is pretty stable and there is many hours put into L10ns to make it stable. So the project is pretty stable. As an result of that, the next evolution of L10ns is really V3. V3 won't maybe be written in JS so it requires a total rewrite of the whole project. That has also constituted to now commits being committed for a while on L10ns. The new L10ns will solve problems in iOS and Android too so not just JS land.

**Comment by reneklacan** [comment]
Thank you for your answer, I am happy to hear that. This project has some really unique features and it's really awesome!

Just out of curiosity, if you are saying that next version maybe won't be written in JS then what do you have in mind? Typescript or something else?

**Comment by tinganho** [comment]
@reneklacan typescript will be a good candidate. Though I'm still evaluating.
