### ISSUE TITLE
Initial setup for l10ns 

### ISSUE THREAD

**Issue by godfern** [tinganho/l10ns#124]
Hi Im trying to run the initial setup of l10ns but facing some issue

Steps i followed

- npm install l10ns -g
- mkdir test
- $ cd test and run the **l10ns init**
-Created a test.js file (test/test.js)
- Added  this code `var requireLocalizations = require('path/to/output/all.js');
var l = requireLocalizations('en-US');
var firstname = l('SIGN_UP->FIRSTNAME');
var lastname = l('SIGN_UP->LASTNAME');`
- var requireLocalizations = require('path/to/output/all.js'); 
 should i create an output folder and add **all.js** file in it? so the path will be require('output/all.js'); 
- After this i tried running l10ns update command. Nothing seems to be creating 

Please help me know if im missing any steps or not doing it properly

Thanks in advance

**Comment by tinganho** [comment]
You must specify your source files in `source` property in your JSON.

```
            "source": [
                "Components/**/*.{ts,tsx}",
                "Contents/**/*.{ts,tsx}"
            ]
```

**Comment by tinganho** [comment]
Be aware to not include the `node_modules` that would be a perf hit.

**Comment by godfern** [comment]
Appreciate your immediate reply. Added my json code 
`{
  "defaultProject": "Language",
  "projects": {
    "Language": {
      "timezones": [
        "America/Los_Angeles"
      ],
      "currencies": [
        "USD"
      ],
      "interface": {
        "autoOpen": true,
        "port": 3001
      },
      "languages": {
        "en-US": "English",
        "zh-CN": "Chinese"
      },
      "defaultLanguage": "en-US",
      "programmingLanguage": "javascript",
      "store": "",
      "output": "localizations/test/output/all.js",
      "source": "localizations/test/test.js"
    }
  }
}`

My folder structure is as follow
[https://drive.google.com/open?id=0BxxhCCYCbjzIWURkVDQ0VmRZLUE](url)

**Comment by tinganho** [comment]
Just notice that the source property should represent all your source js files for whatever application you are building. This will tell the `l10ns` how to update all translation keys.

And I think it must be an array:
```
"source": [
    "test.js"
]
```

**Comment by tinganho** [comment]
You can probably try the following:

```json
"source": [
    "*.js",
    "!node_modules"
]
```

This will add all js files except those in the `node_modules` folder.

**Comment by godfern** [comment]
After adding `"source": [
    "test.js"
]`
still getting this error
`SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /usr/local/lib/node_modules/l10ns/libraries/file.js:248:29
    at tryToString (fs.js:414:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)`

I guess this error is because the resource file en-US.json is empty

@tinganho can you explain following things
- Does the resource file(en-US.jso) gets created once i run `l10ns update` or should i create it.
- Once i create it should i define the structure in the file like this
`{
    "key1": "value1",
    "key2": "value2"
}` 
- var requireLocalizations = require('path/to/output/all.js'); which path should i metion here...i have added
var requireLocalizations = require('output/all.js');

**Comment by godfern** [comment]
@tinganho can you please provide a simple working example

**Comment by tinganho** [comment]
>Does the resource file(en-US.json) gets created once i run l10ns update or should i create it

L10ns will create it and update it for you.

>var requireLocalizations = require('path/to/output/all.js'); which path should i metion here...i have added var requireLocalizations = require('output/all.js');

This is the path to the compiled output.

**Comment by godfern** [comment]
> L10ns will create it and update it for you.
Tried l10ns update but it dint create any resource file(en-US.json)

Please provide a simple example

**Comment by tinganho** [comment]
@godfern can you check out https://github.com/tinganho/l10ns-init?

l10ns update -> updates the storage files.
l10ns compile -> compiles the localisation source files.

**Comment by tinganho** [comment]
@godfern I think you missed to create any `l('LOCALIZATION_STRING')` calls in your source.

If you add in `test.js`
```javascript
l('HELLO_WORLD');
```
and then run `l10ns update`.

It will add the the `HELLO_WORLD` entry in `en-US.json`.

```json
[
  {
    "files": [
      "test.js"
    ],
    "id": "RopyEG7Lh9",
    "key": "HELLO_WORLD",
    "new": true,
    "timestamp": "2016-04-01T07:43:24.843Z",
    "value": "",
    "variables": []
  }
]
```

**Comment by godfern** [comment]
Thanks alot @tinganho for your help...will explore more options with L10ns

**Comment by godfern** [comment]
@tinganho in order to include it in the html file i did the following thing
`<html>
	<head>
		<script type="text/javascript" src="localizations/output/all.js"></script>
		<script type="text/javascript" src="localizations/output/zh-CN.js"></script>
		<script>
			var l = requireLocalizations('zh-CN');
			console.log(l('SIGN_UP->FIRSTNAME'));
		</script>
	</head>	
	<body>

		
	</body>
</html>`

but seems to be not able to console the output.

**Comment by tinganho** [comment]
It should work since I do a check of the window property:

```ts
  if(typeof require === "function" && typeof exports === 'object' && typeof module === 'object') {
    module.exports = requireLocalizations;
  }
  else if (typeof define === "function" && define.amd) {
    define(function() {
      return requireLocalizations;
    });
  }
  else {
    window.requireLocalizations = requireLocalizations;
  }
```

**Comment by godfern** [comment]
> [
  {
    "files": [
      "test.js"
    ],
    "id": "oG9zjA7GUb",
    "key": "SIGN_UP->FIRSTNAME",
    "new": false,
    "timestamp": "2016-04-01T10:18:32.517Z",
    "value": "名",
    "variables": []
  },
  {
    "files": [
      "test.js"
    ],
    "id": "L74qena7tp",
    "key": "SIGN_UP->LASTNAME",
    "new": false,
    "timestamp": "2016-04-01T10:18:32.517Z",
    "value": "",
    "variables": []
  }
]

This is my zh-CN.json. and when i console.log(l('SIGN_UP->FIRSTNAME')) expects the value(名) to print.

But the following function 

> function requireLocalizations(language) {
    return (function(language) {
      return function l(key) {
        if(!(language in localizations)) {
          return 'LANGUAGE_NOT_IN_LOCALIZATIONS: ' + language;
        }
        if(!(key in localizations[language])) {
          return 'KEY_NOT_IN_LOCALIZATIONS: ' + key;
        }
        return localizations[language][key].call(localizations[language], arguments[1]);
      };
    })(language);
  };

This line `return localizations[language][key].call(localizations[language], arguments[1])`  returns an empty string

**Comment by godfern** [comment]
Oh Sorry had not compiled it. Now getting it.

**Comment by godfern** [comment]
@tinganho can't i assign a value when i'm creating the key?. If i run l10ns update it creates the json file but value is en empty string.

**Comment by tinganho** [comment]
You have the following commands:
```js
l10ns interface // opens a web interface
l10ns log // look at all latest added keys
l10ns set @1 "something" // set the nth(first) key from the log
l10ns set @1 "something" -l en-US // set the nth(first) key for `en-US`.
```

Please read the docs.

**Comment by tinganho** [comment]
And there is not default values in l10ns.

**Comment by godfern** [comment]
Ok @tinganho thought we could set default values. Is there a support for handlebars?

**Comment by tinganho** [comment]
No you have to reference them as variables

**Comment by godfern** [comment]
Thanks @tinganho for your support
