### ISSUE TITLE
How to get month abbreviation with capital first letter and without dot?

### ISSUE THREAD

**Issue by asci** [tinganho/l10ns#127]
I need format for **Jun 2016**

`{LLL yyyy}` => Jun. 2016

`{MMM yyyy}` => jun 2016

Any better solution than `replace('.', '')`?

Thanks

**Comment by tinganho** [comment]
Doesn't it already come with a form without dot?

**Comment by tinganho** [comment]
L10ns takes whatever defined in CLDR. It might be that they have updated it with a dot.

**Comment by tinganho** [comment]
I cannot reproduce this.
