### ISSUE TITLE
parsing: line breaks in l()

### ISSUE THREAD

**Issue by tkhyn** [tinganho/l10ns#130]
Hi and thanks for making ``l10ns`` available to the public.

I encountered an issue when using something like:

```javascipt
var quiteLongVariableNameOrFunctionCall = l(
    'QUITE_LONG_TRANSLATION_KEY'
);
```

Indeed, the translation key is not picked up by ``l10ns update``. To fix it I had to put the `l(` and the translation key on the same line.

I guess it's simply a matter of adding a character into a regular expression. I'm on windows and mostly use CRLF line delimiters.

Thanks again !

**Comment by tinganho** [comment]
@tkhyn thanks for reporting I will take a closer look.

**Comment by tkhyn** [comment]
A bit more info:

```
var x = l(
    'NEW_KEY'
);
```

and 

```
var x = l(
    'NEW_KEY');
```

result in no `NEW_KEY` added.

```
var x = l('NEW_KEY'
)
```

results in:

```
  return language.LOCALIZATION_KEY_SYNTAX.exec(fn)[3];
                                                  ^

TypeError: Cannot read property '3' of null
    at Parser.getKey (D:\...\npm\node_modules\l10ns\libraries\parser.js:24:51)
    at D:\...\npm\node_modules\l10ns\libraries\update.js:134:31
    at Array.forEach (native)
    at D:\...\npm\node_modules\l10ns\libraries\update.js:133:17
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

And changing the line endings to LF or CR only has no effect.

(all that with version 2.4.0)

**Comment by tinganho** [comment]
Fixed in https://github.com/tinganho/l10ns/commit/43ad6d353ac82dd6052fabd7646ec54a47643d7f

**Comment by tkhyn** [comment]
Thanks for the quick fix @tinganho
