### ISSUE TITLE
parsing: colon in parameter

### ISSUE THREAD

**Issue by tkhyn** [tinganho/l10ns#131]
I noticed that when using:

```javascript
l('TRANSLATION_KEY', {
    param: 'http://domain'
});
```

2 parameters are added to the translation key when parsing: `http` and `param`. I would expect to only see `param`.

It's a very minor issue but possibly an easy fix. I do not have the time to dive into l10ns codebase to check what causes it but I thought it would be worth mentioning here.

Thanks for looking at it and thanks again for `l10ns`.

**Comment by tinganho** [comment]
@tkhyn I just patched this not a long time ago. Could you please update l10ns.

**Comment by tkhyn** [comment]
@tinganho thanks, indeed, with 2.4.0 it works fine.. Sorry I should have checked the npm package page instead of the repo releases (which shows that the latest release is 2.3)

Closing that, then. Thanks heaps for the very quick reply.
