### ISSUE TITLE
Customize translate function name

### ISSUE THREAD

**Issue by mediafreakch** [tinganho/l10ns#135]
Hello,

Is it possible to customize the translate function name that the parser is looking for in the code?

Some context: I would like to use this library in VueJs templates. For this I need to attach a function to the prototype in order to be available in templates. It's common to prefix those with `$`. So ideally I can set the function name to somewhat like `$translate` or `$t`

**Comment by tinganho** [comment]
You can add this entry to your l10ns.json file.
```json
            "function": {
                "name": "$translate|$t",
                "nameUsingData": "$translate|$t"
            },
```

**Comment by tinganho** [comment]
Note that this is not an official function.

**Comment by mediafreakch** [comment]
Perfect, thanks. Guess would be useful to others as well and would deserve a place in the docs ;)

**Comment by tinganho** [comment]
Maybe the `$` needs to be escaped also with '\\'. It's being passed as arguments to `RegExp`.

**Comment by mediafreakch** [comment]
Hey @tinganho,
There is something weird with those function names. Somehow it only works if the function name is exactly 1 character in length...

**Comment by tinganho** [comment]
Could you try without `$` or escape it \\$``? I have tried with `this\\.l` in one of my projects. So multiple character should work.

**Comment by mediafreakch** [comment]
I'm using the following configuration:

```
{
    "defaultProject": "test",
    "projects": {
        "test": {
            "timezones": [
                "Europe/Zurich"
            ],
            "currencies": [
                "CHF"
            ],
            "interface": {
                "autoOpen": true,
                "port": 3001
            },
            "languages": {
                "en-US": "English",
                "de-CH": "Swiss"
            },
            "defaultLanguage": "en-US",
            "programmingLanguage": "javascript",
            "store": "localizations//",
            "output": "localizations//output",
            "source": ["l10ns.js"],
            "function": {
                "name": "ab",
                "nameUsingData": "ab"
            }
        }
    }
}
```

and my sample "view" file:

```
ab('A')
```

When I now run `l10ns update` the translated `de-CH.json` and `en-US.json` is just an empty array.
If I change the config to `"function": { "name": "a", "nameUsingData": "a" }` it works ( I get the keys in the json files.

**Comment by tinganho** [comment]
@mediafreakch this is a bug. I published a new version `l10ns@2.4.7`. Could you give it a try?

**Comment by mediafreakch** [comment]
@tinganho Wow that was fast. I can confirm that this is working now. What is special is that I can use the dollar sign as follows: 

In view:
```
$trans('KEY')
````

in config:

```
"function": {
  "name": "trans",
  "nameUsingData": "trans"
}
```

If I put the dollar into the config as well it doesn't work (escaped nor unescaped). Not sure if this is intentional, but anyway we can use the dollar sign as shown above.

**Comment by tinganho** [comment]
Do you use this config?
```json
"function": {
  "name": "\\$trans",
  "nameUsingData": "\\$trans"
}
```

**Comment by mediafreakch** [comment]
Yes exactly. Accessing the function name in the view as `$trans('KEY')`. With your suggested config this doesn't work. With the one I showed above it does.

**Comment by tinganho** [comment]
Strange it works for me:
```js

var requireLocalizations = require('./output/all');
var $trans = requireLocalizations('en-US');
var x = $trans(
    'NEW_KEY'
);
console.log($trans('TEST', { test: 1260 }));
console.log($trans('CURRENCY', {
  price: {
    code: 'USD',
    amount: 0
  }
}))
```
```
$ node binaries/l10ns update
[added] NEW_KEY
[added] TEST
[added] CURRENCY
```
I did publish another small change could you try to update to `l10ns@2.4.8`?

**Comment by mediafreakch** [comment]
With the updated version it works also with the `\\$` escaping. You are awesome thanks!
