### ISSUE TITLE
Nested parameters / translation keys

### ISSUE THREAD

**Issue by tkhyn** [tinganho/l10ns#138]
Hello again, I have yet another parsing problem. If I use the following:

```
l('KEY_1', {param: l('KEY_2')})
```

I'd expect my translation store to contain `KEY_1` and `KEY_2` when running `l10ns update`. Here it only contains `KEY_1`.

I've tried to find some way of parsing that but it looks like it will require some sort of recursive regex pattern (!), but I'm posting this here in case somebody more knowledgeable has an idea to solve that. 

The workaround is quite simple (juste use a variable for `l('KEY_2')`, but creating a variable for a single use is not very efficient (nor pretty !).

Thanks again for all the work on l10ns

**Comment by tinganho** [comment]
@tkhyn the translate is not that smart unfortunately. You have to use a variable.

Though choosing to use a regexp pattern instead of fully blown JS parsers it's much more powerful in my opinion. You don't have to keep track of versioning and it can even work across different programming languages.

**Comment by tkhyn** [comment]
Ok, no problem. I did not want to question the use of a regexp, I also think it's the right approach. I was thinking that a few tweaks to the regexp approach could maybe be used to achieve the expected behavior.

**Comment by tinganho** [comment]
It does quite a lot of passes right now, it is not just one regexp. It's a workflow for filtering out the keys.
