### ISSUE TITLE
gsw not supported

### ISSUE THREAD

**Issue by gwildu** [tinganho/l10ns#140]
We tried to localize swiss german (gsw-CH) unfortuately this language is not supported by l10ns as it is not part of cldr-data package. Switching to cldr-data-full package might solve that issue. Or maybe it could be installed if needed to prevent long installation.

fyi: Even with cldr-data-full, we will still have issues because there are some lacking data for gsw on cldr site. We opened a ticket at http://unicode.org/cldr/trac/ticket/9864 to add those data, which was accepted last week. It is scheduled to be fixed at March 15 2017. Until then, as a workaround we might go with a script copying the missing data from cldr-data-full and/or enhancing them with data on our own until the cldr ticket is solved.

**Comment by tinganho** [comment]
L10ns already uses the full tier. If this was added in CLDR hopefully we can just switch to CLDR 31.

**Comment by gwildu** [comment]
I found the reason, why I didn't get the gsw files. I installed l10ns as dev dependency, not globally. Is there a reason, why it has to be installed globally? The downside is, that you can't install it via package.json then...

**Comment by tinganho** [comment]
L10ns is global program. Thus it need to be installed globally?

**Comment by gwildu** [comment]
I don't get the point, maybe I'm missing something (I'm not very familiar with criteria, when a package should be globally and when not, for now dependency packages did the job for me...). 

When we use it in our project and as a project dependency, it would be nice, it could be installed as dev dependency. Reasons for it, could be, when a new team member starts, he executes npm install and all dependencies are installed, or when a build is triggered on circle-ci or travis, all dependencies are installed and l10ns compile can be excecuted after install.

We have it installed now for some time as dev dependency and so far everything is working fine, except that not the full cldr-data is installed. I just would like to understand why it is intended to be global and if we have to change the way we are using it today.

**Comment by tinganho** [comment]
L10ns needs to be installed globally because the executable `l10ns` needs to be. Though the executable under `node_modules` might also work, though it is not the recommended way of using l10ns.

Even though l10ns is a dev dependency, it doesn't mean it needs to be under "devDependency" in your `package.json`. L10ns is not a runtime library it's a tool. And just like bower, grunt, yarn etc. L10ns also need to be installed globally.

**Comment by tinganho** [comment]
Closing because it seems solved.

**Comment by gwildu** [comment]
Yes, the ticket on unicode has ben solved. I will try to find some time for testing it, but I guess it should work now.
