### ISSUE TITLE
Static files not served

### ISSUE THREAD

**Issue by malcolmvr** [tinganho/l10ns#151]
The interface stopped serving /vendor files for me.
I'm running node v6.9.1

I can fix by adding:
```
    if (global.ENV === 'development') {
      app.use(express.static(path.join(__dirname, '../')));
    }
```
at line 51 of /configurations/app.js

The function at line 15 of /configurations/app.js is not fired.

I'm getting a warning: (node:4524) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
that does not seem to be related (I changed the GLOBAL references to global and the issue remains).

**Comment by tinganho** [comment]
I cannot replicate this in node v.6.9.2

**Comment by malcolmvr** [comment]
Just installed 6.9.4 and the issue remains for me.
I reverted my project to a commit that I know the interface was working on - still have the issue.
Other teammates having the same issue.

Really not sure what's up with this but is potentially a bug. Let's see if anyone else reports it.

**Comment by tinganho** [comment]
I removed that check right now. Please install l10ns@2.4.9 to test it out.

**Comment by malcolmvr** [comment]
Installed 2.4.9 and the issue no longer occurs.
