### ISSUE TITLE
can't install on node 8

### ISSUE THREAD

**Issue by cvlmtg** [tinganho/l10ns#160]
Hi, I've tried to install l10ns on node.js 8 and this is what happens (it installs fine with node 6.10.2)

```
I ~ npm install -g l10ns
npm WARN deprecated tough-cookie@0.12.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated npmconf@2.0.9: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/Users/matteo/.nvf/installed/node-8.0.0/bin/l10ns -> /Users/matteo/.nvf/installed/node-8.0.0/lib/node_modules/l10ns/binaries/l10ns

> cldr-data@28.0.5 install /Users/matteo/.nvf/installed/node-8.0.0/lib/node_modules/l10ns/node_modules/cldr-data
> node install.js

Whops {} deepEqual { url:
   [ 'https://github.com/unicode-cldr/cldr-core/archive/28.0.2.zip',
     'https://github.com/unicode-cldr/cldr-segments
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cldr-data@28.0.5 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@28.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/matteo/.npm/_logs/2017-06-05T08_24_52_021Z-debug.log
```

**Comment by tinganho** [comment]
I think I will just wait a bit with this one. I remember node 7 had similar problem during its launch.

**Comment by cvlmtg** [comment]
👍

**Comment by tinganho** [comment]
tracked here https://github.com/rxaviers/cldr-data-downloader/issues/24

**Comment by jackTheRipper** [comment]
Hi,

I was able to fix the issue with the `deepEqual` by upgrading my dependencies as it follows:

```json
"cldr-data": "^31.0.2",
 "cldrjs": "^0.4.8",
```

However, when I am running `npm i -g l10ns`, I am facing another issue saying: 

```
Whops ENOENT: no such file or directory, chmod '/usr/lib/node_modules/l10ns/node_modules/cldr-data/.gitattributes'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cldr-data@31.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cldr-data@31.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/go/.npm/_logs/2017-10-10T09_17_15_774Z-debug.log
```

The issue happens **only** when I am using the `-g` flag.

I am using Node 8.6.0 and NPM 5.4.2.

As a workaround, I am now running in my Docker image the following commands to make `l10ns` available globally:

```
&& cd /usr/lib \
&& npm install https://github.com/jackTheRipper/l10ns.git#2.3.2
```

It works, but it's dirty:

```
# which l10ns
/usr/bin/l10ns
```

I am using Debian Jessie here.

Even if a part of the issue is external, any plans for a dependency update?

**Comment by tinganho** [comment]
I can try to update to CLDR 31 to see if it resolves the problem.

**Comment by jackTheRipper** [comment]
@tinganho : this should fix the original issue. But you will still have the one attached to `-g` flag

**Comment by tinganho** [comment]
@jackTheRipper suggestion seem to work. I published a new version of l10ns.

**Comment by tinganho** [comment]
Actually I'm getting the error `Whops ENOENT: no such file or directory, chmod '/usr/lib/node_modules/l10ns/node_modules/cldr-data/.gitattributes'`

**Comment by tinganho** [comment]
It seems like this is related to some npm permission issues. See https://github.com/rxaviers/cldr-data-downloader/issues/24#issuecomment-338419717

**Comment by ghost** [comment]
Hi @tinganho, the issue you have is the one I described when you try to perform an installation with `node i -g l10ns`.

I explained in this issue how to tricks it. But it's a hack. I hope the issue you referenced will be fixed soon.

**Comment by malcolmvr** [comment]
Still seeing this issue with node 8.11.1 and npm 5.6.0. Can the cldr-data dependency be upgraded to the latest?

**Comment by tinganho** [comment]
@malcolmvr upgrading to the latest CLDR doesn't solve the problem. I'm sorry for the inconvenience. 

As I recalled it, there was a problem with NPM. I've tried multiple times to tackle this issue. Without getting a solution.

This is the relevant comment:
https://github.com/rxaviers/cldr-data-downloader/issues/24#issuecomment-338419717

**Comment by tinganho** [comment]
Upgrading it won't solve the problem though. Sorry for the inconvience. But I think this problem resides in NPM. I've spent quite a lot of time trying to resolve this issue, but without any success so far.

**Comment by tinganho** [comment]
I think l10ns now works with node 8. I updated cldr-data package.

On Mac I have to run with the `--unsafe-perm` flag:
```
sudo npm install l10ns -g --unsafe-perm
```
