### ISSUE TITLE
Cannot find module 'cldr-data/defaultContent.json'

### ISSUE THREAD

**Issue by D4rkL1ch** [tinganho/l10ns#169]
Hey,
I am using l10ns library and today I noticed that none of the commands are working. Whenever I try to search, update or call interface I get error:
```> l10ns interface

module.js:540
    throw err;
    ^

Error: Cannot find module 'cldr-data/defaultContent.json'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (<project_directory>\node_modules\l10ns\libraries\MessageFormat\index.js:16:26)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
I have version 2.4.11 installed, I tried to install version 2.4.41, but I get same error.
Is there anyway to fix this?

**Comment by tinganho** [comment]
Which node version are you using?

**Comment by D4rkL1ch** [comment]
Node version is 9.9.0.

**Comment by D4rkL1ch** [comment]
Hey, bumping the issue.
Did you manage to check what might be an issue?

**Comment by tinganho** [comment]
@D4rkL1ch Right now, I only get the error https://github.com/tinganho/l10ns/issues/160. Which I don't really know how to fix. I think NPM changed something.

But I guess your OS is not Mac? Which OS are you using?

**Comment by D4rkL1ch** [comment]
I am using Windows and node.js for Windows. My colleagues using Linux also do get that error.

**Comment by rhalukongor** [comment]
I remember facing the same thing. IIRC `cd node_modules/cldr-data && npm install` fixes it.

Check it here:
https://github.com/tinganho/l10ns/issues/117

**Comment by tinganho** [comment]
I will try to check this out as soon as I can, though I usually cannot get pass #160. I might endup inlining the whole CLDR data node_module.

**Comment by D4rkL1ch** [comment]
@rhalukongor thanks, that does work.

**Comment by hexadecy** [comment]
@tinganho can you please publish a working version for node8+ on npmjs?

"cldr-data": "33.0.0" works for me.
I fork it: [hexadecy/l10ns](https://github.com/hexadecy/l10ns)
But I don't know how to correctly build this project...

**Comment by tinganho** [comment]
@hexadecy I published a new version. Could you give it a try?

On Mac I have to run with `--unsafe-perm` flag:
```
sudo npm install l10ns -g --unsafe-perm
```

**Comment by hexadecy** [comment]
@tinganho yes it works on Windows 10, node v8.11.3 and npm 6.4.1.
Command prompt as **administrator**:
```
npm install l10ns -g
```
