### ISSUE TITLE
Failed at the cldr-data@31.0.2 install script

### ISSUE THREAD

**Issue by abhijit-padhy** [tinganho/l10ns#172]
`cldr-data@31.0.2` package installation fails in my application. I tried removing node_modules folder and reinstalling different versions of `cldr-package` with different node versions (using nvm 0.39.0) but all fail. I installed the latest package one time but it threw error "missing file 'cldr-data/availableLocales.json'".

Currently I am using: 
node: 12.10.0
npm: 6.10.3
zsh shell in terminal
macOS BigSur

FYI I referred all possible tickets raised similar to this issue but no success result. `sudo npm install l10ns -g --unsafe-perm` from https://github.com/tinganho/l10ns/issues/160 also fails. 

PFA error log:

![Screenshot 2021-10-26 at 12 26 53 AM](https://user-images.githubusercontent.com/28405350/138826276-d9ccbeb9-dae2-4ed8-aebc-bb3b30fd649e.jpg)

**Comment by abhijit-padhy** [comment]
Probably wrong place to raise this issue. So I duplicated it [here](https://github.com/rxaviers/cldr-data-npm/issues/74) and closing this ticket.

**Comment by GEMI** [comment]
Same here.
