### ISSUE TITLE
Interface not working

### ISSUE THREAD

**Issue by nmn** [tinganho/l10ns#68]
`l10ns interface` command is not working

with node 0.11.14
`Cannot read property 'filename' of undefined`

with node 0.10.33
```
dyld: lazy symbol binding failed: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/l10ns/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup

dyld: Symbol not found: _node_module_register
  Referenced from: /usr/local/lib/node_modules/l10ns/node_modules/libxmljs/build/Release/xmljs.node
  Expected in: dynamic lookup

Trace/BPT trap: 5
```

I'm not being able to find out more to help fix this.

Thanks for the amazing utility.

**Comment by tinganho** [comment]
Do you mind sharing which OS you are using? I will look into this issue tomorrow.

**Comment by nmn** [comment]
Using a Macbook Air, on Yosemite.

**Comment by tinganho** [comment]
I'm not able reproduce the problem you have at least not in node v0.10.33 on a Macbook Pro. Can you try to run the installation again. "npm install l10ns -g"? Also check that the installation has no interrupted errors.

**Comment by nmn** [comment]
Hi.
I tried everything. I re-installed l10ns, I tried a different computer, I updated npm, but I get exactly the same results.

Perhaps I'm doing something wrong. I'm only trying to follow the guide on the website with a test project. This is what my file structure looks like:
```
test
  - .l10ns
  - localization
    - output
      - all.js
      - en-US.js
      - zh-CN.js
    - en-US.json
    - zh-CN.json
  - l10ns.json
  - test.js
```

test.js is -
```
var requireLocalizations = require('./localizations/output/all');
var l = requireLocalizations('zh-CN');
var firstname = l('SIGN_UP__FIRSTNAME');
var lastname = l('SIGN_UP__LASTNAME');

console.log(firstname);
```

l10ns.json is
```

{
  "defaultProject": "test",
  "projects": {
    "test": {
      "currencies": [
        "USD"
      ],
      "interface": {
        "autoOpen": true,
        "port": 5000
      },
      "locales": {
        "en-US": "English (US)",
        "zh-CN": "Mandarin (China)"
      },
      "defaultLocale": "en-US",
      "programmingLanguage": "javascript",
      "store": "localizations/",
      "output": "localizations/output",
      "source": ["./test.js"]
    }
  }
}
```

Am I missing something? Thanks.

**Comment by tinganho** [comment]
The directory `test/localization` should end with an s (`test/localizations`) ?

**Comment by nmn** [comment]
it does. Sorry for the error. I was more worried if I need to write code to make the interface work.

**Comment by tinganho** [comment]
Ok the interface should work. It just need the storage files. Everything seems ok. Though I think the installation of L10ns is still wrong. L10ns uses `libxmljs` to parse some XML files.

Can you just check if we are using the same libxmljs version? Just check the file /usr/local/lib/l10ns/node_modules/libxmljs/package.json and then the property `version`? I'm using 0.11.1

**Comment by nmn** [comment]
I have the same version.

Though the path for me was: `/usr/local/lib/node_modules/l10ns/node_modules/libxmljs/package.json`

I'm guessing that was just a typo.

**Comment by tinganho** [comment]
I just found this issue: https://github.com/rvagg/node-levelup/issues/240

And I have been able to reproduce your bug. After installing node 0.11.13. It seems like this is an node-issue

**Comment by tinganho** [comment]
Though I only got the linking issue not the undefined issue. I think you somehow you must do a clean install because it works for me when I downgrade to node 0.10.35 again.

**Comment by nmn** [comment]
So, I re-installed l10ns and now it works. Looks like the issue happens if you install when Node 0.11 is active.

Thanks for the help!

**Comment by tinganho** [comment]
Ok good @nmn I will soon launch L10ns with Dateformat and timezone support. So that there is no need to use http://momentjs.com/. And in that release I throw out all C-binding libraries. So this issue will not appear if you want to use L10ns with node 0.11.
