### ISSUE TITLE
update issue on windows

### ISSUE THREAD

**Issue by chevdor** [tinganho/l10ns#70]
Hi,

I am getting the following message on windows:
 D:\Projects\l10ns>l10ns update
  [added] PAGE
  [error] Localizations update failed

 D:\Projects\l10ns>l10ns log
  ENOENT, open 'D:\Projects\10ns\D:\Projects\l10ns\localizations\en-US.json'

**Comment by chevdor** [comment]
I guess the issue is in index.js around
```
 project.store = path.join(project.root, project.store);
    if(!/^\//.test(project.store)) {
      project.store = path.join(project.root, project.store);
    }
```

**Comment by chevdor** [comment]
I guess a dirty fix would be to change:
```
   if(!/^\//.test(project.store) && !/^\w\:/.test(project.store) ) {
      project.store = path.join(project.root, project.store);
    }
```
into
```
if(!/^\//.test(project.store) && !/^\w\:/.test(project.store) ) {
   project.store = path.join(project.root, project.store);
}
```
in index.js

**Comment by tinganho** [comment]
Thanks @chevdor for reporting it. I will try to push out a release ASAP since this is a critical bug.

**Comment by tinganho** [comment]
@chevdor It is now launched l10ns@1.0.1
