### ISSUE TITLE
l10ns --version returns the version, -V not

### ISSUE THREAD

**Issue by chevdor** [tinganho/l10ns#72]
Hi,

I installed l10ns globally.
Running l10ns --version works fine from a random location.
Running l10ns -V from the same random location (= no l10ns project) complains that I am not inside a l10ns project.

**Comment by tinganho** [comment]
Thanks @chevdor I will try to fix this issue until next release. Which will include date formatting.

**Comment by tinganho** [comment]
Fixed now on master
