### ISSUE TITLE
Remaining fixes for 2.0

### ISSUE THREAD

**Issue by tinganho** [tinganho/l10ns#73]
- [x] New landing page
- [x] Use cldr-data and cldrjs
- [x] Fix content overflowing on locale picker
- [x] Fix locale to languageModifier mapping
- [x] Fix compilation of locale to languageModifier mapping
- [x] Insight to use child process to speed up CLI methods
- [x] Fix animation issue with fade-in-fade-out of main content
- [x] Fix docs that says `Tuessay`
- [x] Fix docs for period 
- [x] Remove developer analytics reporting on interface
- [x] Add compile button on interface
- [x] Add negative floating point and infinity exact cases to plural format
- [x] Regular long localized format example should have zero padding

**Comment by focusaurus** [comment]
Any estimate whether we can expect this soon? I'm currently having to install from the git master branch, `npm install --development`, run `grunt dot`, etc to get a version with my fixes for language-code-only locales. Other than that, I think I have a l10ns-enable project ready to release to QA.

**Comment by tinganho** [comment]
I'm waiting on an issue to be fixed for the npm module `cldr-data` https://github.com/rxaviers/cldr-data-npm/issues/6#issuecomment-74793777. 

I will release directly after the issue is fixed.

**Comment by tinganho** [comment]
Hi @focusaurus I just released version 2.0. Please check it out. I need to change name on some settings. It just issues warning about it. Please checkout the change log: https://github.com/tinganho/l10ns/blob/master/CHANGELOG.md.

**Comment by focusaurus** [comment]
Tried it and it's working fine for us. Thanks!
