### ISSUE TITLE
Fix cldr-data paths

### ISSUE THREAD

**Issue by tinganho** [tinganho/l10ns#92]

**Comment by focusaurus** [comment]
Is this this issue: `Cannot find module './json/supplemental/likelySubtags'`? If so, a workaround seems to be:

```sh
cd node_modules/l10ns
npm install cldr-data@26.0.9
```

26.0.8 and 26.0.9 seem OK but 26.0.10 breaks.

**Comment by tinganho** [comment]
There was a breaking API change in `cldr-data` https://github.com/rxaviers/cldr-data-npm/issues/10. As of know I fixed the version to 26.0.8.
