### ISSUE TITLE
l10ns update function skips some keys

### ISSUE THREAD

**Issue by gregod** [tinganho/l10ns#93]
Given the input file below and default settings:
```javascript
function m(tag,content){} // stub

m("div", [
	m("strong", l("C1")),
	m("p", l("D1"))
])

var q = l("A1");
```
only **A1** & **C1** are found. **D1** is ignored!

**Comment by tinganho** [comment]
@gregod I have published the solution to NPM. Let me know if there are any problem.

**Comment by gregod** [comment]
Perfect. Works as expected now. Thanks a lot.
